### ISSUE TITLE
BNO055 reset yields a OS Error: [Errno121] Remote I/O Error

### ISSUE THREAD

**Issue by angela804** [adafruit/Adafruit_Python_PureIO#28] opened 2022-10-10 07:05 UTC
I'm creating a system that's supposed to utilize the ability of the BNO055 sensor to know the angle for rotation.

However, for the system to be continuous and long lasting, I need to implement a reset function where it resets the current reading of the BNO055 back to zero.

So, I created this function inside the adafruit_bno055.py file under BNO055_I2C class, and around line 778 to implement the reset. 

```
def _resetBNO055(self):
       super()._init__()
```

The system did work as it has the ability to reset the sensor reading back to 0. However, after a short while let's say for a few minutes, it shows this error. Did I miss to put something inside the reset function? Or did the delays of getting signals messed up. I'm not really sure if this error is about the code or partly the hardware.

```
 File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/Downloads/Multiprocess Copy/launcher.py", line 73, in runRover
    rover.rotate()
  File "/home/pi/Downloads/Multiprocess Copy/rover.py", line 109, in rotate
    self.stop()
  File "/home/pi/Downloads/Multiprocess Copy/rover.py", line 129, in stop
    self.headingSensor._resetBNO055()
  File "/home/pi/.local/lib/python3.9/site-packages/adafruit_bno055.py", line 781, in _resetBNO055
    super().__init__()
  File "/home/pi/.local/lib/python3.9/site-packages/adafruit_bno055.py", line 216, in __init__
    self.set_normal_mode()
  File "/home/pi/.local/lib/python3.9/site-packages/adafruit_bno055.py", line 741, in set_normal_mode
    self._write_register(_POWER_REGISTER, _POWER_NORMAL)
  File "/home/pi/.local/lib/python3.9/site-packages/adafruit_bno055.py", line 789, in _write_register
    i2c.write(self.buffer)
  File "/home/pi/.local/lib/python3.9/site-packages/adafruit_bus_device/i2c_device.py", line 101, in write
    self.i2c.writeto(self.device_address, buf, start=start, end=end)
  File "/home/pi/.local/lib/python3.9/site-packages/busio.py", line 168, in writeto
    return self._i2c.writeto(address, memoryview(buffer)[start:end], stop=stop)
  File "/home/pi/.local/lib/python3.9/site-packages/adafruit_blinka/microcontroller/generic_linux/i2c.py", line 52, in writeto
    self._i2c_bus.write_bytes(address, buffer[start:end])
  File "/home/pi/.local/lib/python3.9/site-packages/Adafruit_PureIO/smbus.py", line 314, in write_bytes
    self._device.write(buf)
OSError: [Errno 121] Remote I/O error
```

**Comment by makermelissa** [comment] 2022-10-11 15:36
I'm not sure exactly why it would be behaving this way, but since it is an OSError, the issue is likely deeper than this library goes and I would expect something similar with the official python3-smbus library (which we don't use anymore because bindings aren't available on some versions of linux).

**Comment by angela804** [comment] 2022-10-12 06:22
@makermelissa I think I had it wrong. I got two errors, this one and the other one is a bad chip id. I fixed the bad chip id after adding `dtparam=i2c_arm_baudrate=10000` in my rpi's boot config.


The OSError however shows up whenever there's a sudden or unexpected movement of my robot in the middle of the bno055 doing it's purpose. Does the OS Error shows whenever there are also hardware issues on the bno055 part?

**Comment by makermelissa** [comment] 2022-10-12 18:39
Ok yeah, I forgot the BNO055 requires clock stretching enabled (https://learn.adafruit.com/circuitpython-on-raspberrypi-linux/i2c-clock-stretching) which you basically did. It's really just slowing down the I2C bus. You can try some slower values to see if that helps.

Upon doing some digging, `OSError: [Errno 121] Remote I/O error` just means it's having trouble communicating with the Pi. Perhaps you can place this inside a try/except block and retry a few times if it's thrown.

As a last resort, it looks like the BNO055 supports UART communication (See [CircuitPython & Python Usage](https://learn.adafruit.com/adafruit-bno055-absolute-orientation-sensor/python-circuitpython#circuitpython-and-python-usage-2974413)).

If you still aren't able to get up and running, I'd suggest posting on the [Adafruit Forums](https://forums.adafruit.com/) or over on [Discord](https://adafru.it/discord).

There really isn't anything to be fixed in this library, so I'm going to close this. Feel free to re-open if it turns out that there really is a bug in here.

**Closed as completed by makermelissa** 2022-10-12 18:39 UTC
